[package]
name = "breaker_machines_native"
version = "0.5.5"
edition = "2024"
authors = ["Abdelkader Boudih <oss@seuros.com>"]
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
breaker-machines = { workspace = true }
magnus = { version = "0.8.2", features = ["embed"] }

[build-dependencies]
rb-sys = "0.9"
