[workspace]
members = ["ext/breaker_machines_native/core", "ext/breaker_machines_native/ffi"]
resolver = "2"

[workspace.dependencies]
breaker-machines = { path = "./ext/breaker_machines_native/core" }
state-machines = "0.6"
chrono-machines = "0.2.1"
